services:
  db:
    image: postgres:16-alpine
    container_name: pingpong_db
    environment:
      - POSTGRES_DB=pingpong
      - POSTGRES_USER=pingpong
      - POSTGRES_PASSWORD=pingpong
    ports:
      - "5432:5432"      # optional; helpful for a GUI client
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pingpong -d pingpong"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pingpong_api
    env_file:
      - .env.dev
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./backend/app:/app/app:rw
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --reload

volumes:
  pg_data:
