# docker-compose.yml (root)
version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pingpong_api
    env_file:
      - .env.dev
    environment:
      - TZ=${TZ}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app:rw
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --reload
